#pragma once

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 6
#define MOUSEKEY_MAX_SPEED 5
#define MOUSEKEY_TIME_TO_MAX 20
#define MOUSEKEY_WHEEL_DELAY 20
#define MOUSEKEY_WHEEL_INTERVAL 60
#define MOUSEKEY_WHEEL_MAX_SPEED 2
#define MOUSEKEY_WHEEL_TIME_TO_MAX 30

//#define USB_WAIT_FOR_ENUMERATION
//#define NO_SUSPEND_POWER_DOWN - testing now - probably not necessary
#define USB_SUSPEND_WAKEUP_DELAY 50
#define NO_USB_STARTUP_CHECK
